# Generated by Django 5.1.3 on 2024-12-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0011_students_teachers_marks_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loginpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
